In [1]:
import numpy as np
from scipy.sparse import csr_matrix, coo_matrix
import time
from threading import Thread
from threading import Event
from SpArchClasses import MatrixAFetcher
from SpArchClasses import DistanceListBuilder
from SpArchClasses import MatrixBPrefetcher
from SpArchClasses import MultiplierArray
from SpArchClasses import MergeTree
from SpArchClasses import Scheduler
from SpArchClasses import Memory

In [2]:
LLB_TILE_SIZE = 300
PE_TILE_SIZE = 150
NUM_PES = 120
I = 1000
K = 1000
J = 1000
NUM_INTS = 1000

gen = np.random.default_rng()
data1 = gen.integers(1,10,NUM_INTS)
row1 = gen.integers(0,I,NUM_INTS)
col1 = gen.integers(0,K,NUM_INTS)

data2 = gen.integers(1,10,NUM_INTS)
row2 = gen.integers(0,K,NUM_INTS)
col2 = gen.integers(0,J,NUM_INTS)
i1 = csr_matrix(coo_matrix((data1, (row1, col1)), shape=(I, K)))
i2 = csr_matrix(coo_matrix((data2, (row2, col2)), shape=(K, J)))

In [3]:
print(i1.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
print(i2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
NUM_CHANNELS = 16
BANDWIDTH_PER_CHANNEL = 8
NUM_INPUT_FIFOS = 64
MERGE_SIZE = 1

AL = MatrixAFetcher(i1)
DL = DistanceListBuilder()
MBP = MatrixBPrefetcher(i2)
MPA = MultiplierArray()
MT = MergeTree(MERGE_SIZE)
M = Memory(NUM_CHANNELS, BANDWIDTH_PER_CHANNEL)
S = Scheduler(AL,MT,DL,MBP,MPA,NUM_INPUT_FIFOS)

AL.setDLB(DL)
AL.setMemory(M)

DL.setMBP(MBP)
DL.setMultiplier(MPA)

MBP.setMultiplier(MPA)
MBP.setDistanceListBuilder(DL)
MBP.setMemory(M)

MPA.setMergeTree(MT)
MPA.setScheduler(S)

MT.setScheduler(S)

endFlag = True



In [6]:

ALEvent = Event()
ALEvent.set()
Thread(target=AL.running,args=[ALEvent]).start()

MBPEvent = Event()
MBPEvent.set()
Thread(target=MBP.running,args=[MBPEvent]).start()

MPAEvent = Event()
MPAEvent.set()
Thread(target=MPA.running,args=[MPAEvent]).start()

MTEvent = Event()
MTEvent.set()
Thread(target=MT.running,args=[MTEvent]).start()

count = 0
while endFlag:
    count += 1
    ALEvent.clear()
    MBPEvent.clear()
    MPAEvent.clear()
    MTEvent.clear()

    if not AL.endFlag:
        ALEvent.wait()
    if not MBP.endFlag:
        MBPEvent.wait()
    if not MPA.endFlag:
        MPAEvent.wait()
    if not MT.endFlag:
        MTEvent.wait()
    
    endFlag = not (AL.endFlag and MBP.endFlag and MPA.endFlag and MT.endFlag)
    
    if not MPA.endFlag:
        MPA.loadInputs()
    M.cycle()

print(count)

1
1
5523


In [7]:
data = []
i = []
j = []
for x in MT.partialMatrices[-1]:
    data.append(x[0])
    i.append(x[1])
    j.append(x[2])

total = coo_matrix((data,(i,j)),shape=(I,K))
print(total.toarray())
print(np.matmul(i1.toarray(),i2.toarray()))
print(np.equal(total.toarray(), np.matmul(i1.toarray(),i2.toarray())))
print(np.allclose(total.toarray(),np.matmul(i1.toarray(),i2.toarray()),rtol=0.01))


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]
True
