In [31]:
from ExTensorClasses import DRAMIntersector
from ExTensorClasses import LLBIntersector
from ExTensorClasses import PEArray
from ExTensorClasses import PEIntersector
from ExTensorClasses import CSFNode
from ExTensorClasses import coo_to_csf
from ExTensorClasses import print_csf_tree
import numpy as np
from scipy.sparse import coo_matrix
from threading import Thread
from threading import Event

In [32]:
LLB_TILE_SIZE = 300
PE_TILE_SIZE = 150
NUM_PES = 120
I = 1000
K = 1000
J = 1000
NUM_INTS = 1000
MODE = "NoSkip"

# Options: NoMerge, Skip, NoSkip

endFlag = True
dramIntersector = DRAMIntersector(MODE)
llbIntersector = LLBIntersector(MODE, LLB_TILE_SIZE, PE_TILE_SIZE)
peArray = PEArray(NUM_PES)
peIntersectorList = []
for x in range(NUM_PES):
    peIntersectorList.append(PEIntersector(MODE, LLB_TILE_SIZE, min(PE_TILE_SIZE, NUM_INTS),x))
dramIntersector.setNext(llbIntersector)
llbIntersector.setNext(peArray)
peArray.setNext(peIntersectorList)



gen = np.random.default_rng()
data1 = gen.integers(1,10,NUM_INTS)
row1 = gen.integers(0,I,NUM_INTS)
col1 = gen.integers(0,K,NUM_INTS)

data2 = gen.integers(1,10,NUM_INTS)
row2 = gen.integers(0,K,NUM_INTS)
col2 = gen.integers(0,J,NUM_INTS)
i1 = coo_matrix((data1, (row1, col1)), shape=(I, K))
i2 = coo_matrix((data2, (row2, col2)), shape=(K, J))

input1 = coo_to_csf(i1,LLB_TILE_SIZE,LLB_TILE_SIZE,PE_TILE_SIZE,PE_TILE_SIZE,False)
input2 = coo_to_csf(i2,LLB_TILE_SIZE,LLB_TILE_SIZE,PE_TILE_SIZE,PE_TILE_SIZE,True)


In [33]:
dramIntersector.input(input1, input2, K, LLB_TILE_SIZE)

dIEvent = Event()
dIEvent.set()
Thread(target=dramIntersector.running,args=[dIEvent]).start()

lIEvent = Event()
lIEvent.set()
Thread(target=llbIntersector.running,args=[lIEvent]).start()

peAEvent = Event()
peAEvent.set()
Thread(target=peArray.running,args=[peAEvent]).start()

peThreadList = [None] * NUM_PES
peEventList = [None] * NUM_PES
for x in range(NUM_PES):
    peEventList[x] = Event()
    peEventList[x].set()
    Thread(target=peIntersectorList[x].running,args=[peEventList[x]]).start()
count = 0
while endFlag:
    count += 1
    dIEvent.clear()
    lIEvent.clear()
    peAEvent.clear()
    for event in peEventList:
        event.clear()

    if not dramIntersector.endFlag:
        dIEvent.wait()
    if not llbIntersector.endFlag:
        lIEvent.wait()
    if not peArray.endFlag:
        peAEvent.wait()
    for pe in range(NUM_PES):
        if not peIntersectorList[pe].endFlag:
            peEventList[pe].wait()
        else:
            peIntersectorList[pe].numEmptyCycles+=1 # if the PE is at EOF but the overall processing isn't finished, increment the number of wasted cycles

    endFlag = not (dramIntersector.endFlag and llbIntersector.endFlag and peArray.endFlag)
    for x in range(NUM_PES):
        endFlag = endFlag or not peIntersectorList[x].endFlag
    
print(count)
total = 0
for x in range(NUM_PES):
    print("PE#" + str(x) + " Hardware Utilization:" + '%.2f' % ((1 -round(peIntersectorList[x].numEmptyCycles/count,4)) * 100) + "%")
    total += (1 -round(peIntersectorList[x].numEmptyCycles/count,4)) * 100
    
print("Average Hardware Utilization: " + str(total/NUM_PES))

print("LLB Memory Usage:", llbIntersector.memoryAccessBytes, "LLB memory wasted cycles: ", llbIntersector.memoryWastedCycles )
print("DRAM Memory Usage:", dramIntersector.memoryAccessBytes, "DRAM memory wasted cycles: ", dramIntersector.memoryWastedCycles )

3781
PE#0 Hardware Utilization:65.78%
PE#1 Hardware Utilization:63.58%
PE#2 Hardware Utilization:52.95%
PE#3 Hardware Utilization:49.01%
PE#4 Hardware Utilization:71.70%
PE#5 Hardware Utilization:66.12%
PE#6 Hardware Utilization:65.49%
PE#7 Hardware Utilization:63.21%
PE#8 Hardware Utilization:73.53%
PE#9 Hardware Utilization:59.24%
PE#10 Hardware Utilization:62.39%
PE#11 Hardware Utilization:59.93%
PE#12 Hardware Utilization:75.67%
PE#13 Hardware Utilization:61.12%
PE#14 Hardware Utilization:95.66%
PE#15 Hardware Utilization:87.97%
PE#16 Hardware Utilization:77.70%
PE#17 Hardware Utilization:62.68%
PE#18 Hardware Utilization:75.22%
PE#19 Hardware Utilization:68.90%
PE#20 Hardware Utilization:77.78%
PE#21 Hardware Utilization:62.68%
PE#22 Hardware Utilization:81.12%
PE#23 Hardware Utilization:73.10%
PE#24 Hardware Utilization:78.71%
PE#25 Hardware Utilization:62.71%
PE#26 Hardware Utilization:64.40%
PE#27 Hardware Utilization:59.22%
PE#28 Hardware Utilization:71.22%
PE#29 Hardware Util

In [34]:
r = []
c = []
v = []
for i,output in enumerate(peIntersectorList):
    for o in output.output:
        v.append(o[0])
        r.append(o[1])
        c.append(o[2])
    
est = coo_matrix((v,(r,c)),(I,K)).toarray()
actual = np.matmul(i1.toarray(),i2.toarray())
print(est)
print(actual)
print(np.equal(actual, est))
print(np.allclose(actual,est,0.0001,0.0001))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]
True


In [35]:
def coo_to_small_csf(coo_matrix):
    root = CSFNode(None)

    for i, j, data in zip(coo_matrix.row, coo_matrix.col, coo_matrix.data):
        current_node = root
        
        # Traverse the tree based on the coordinates
        # NOTICE: b comes before a because THE LLB TILES ARE COLUMN MAJOR, NOT ROW MAJOR. BECAUSE THE MULTIPLICATION IS B-STATIONARY, THE MATRIX MUST BE COL MAJOR FOR THE FIRST TWO COORDINATES
        # WHEN DOING A-STATIONARY, WE WANT BOTH AS ROW-MAJOR, AND WHEN OUTPUT STATIONARY WE WANT A AS ROW MAJOR, AND B AS COL MAJOR
        for coord in [j, i]:
            if coord not in current_node.children:
                current_node.children[coord] = CSFNode(None)
            current_node = current_node.children[coord]

        # Set the leaf node value to the data value
        if current_node.value != None:
            current_node.value += data
        else:
            current_node.value = data

    return root

In [36]:
LLB_TILE_SIZE = 2
PE_TILE_SIZE = 1
NUM_PES = 15

data1 = [1,1,1,1,1]
row1 = [1, 2, 3, 4, 0]
col1 = [1, 1, 1, 2, 4]

data2 = [1,1,1,1,1]
row2 = [1, 1, 3, 2, 0]
col2 = [1, 2, 1, 2, 4]
i1 = coo_matrix((data1, (row1, col1)), shape=(5, 5))
i2 = coo_matrix((data2, (row2, col2)), shape=(5, 5))

input1 = coo_to_small_csf(i1)
input2 = coo_to_small_csf(i2)

LLB_TILE_SIZE = 100
PE_TILE_SIZE = 50
NUM_PES = 15

endFlag = True
dramIntersector = DRAMIntersector(True)
llbIntersector = LLBIntersector(True)
peArray = PEArray(NUM_PES)
peIntersectorList = []
for x in range(NUM_PES):
    peIntersectorList.append(PEIntersector(True, LLB_TILE_SIZE, PE_TILE_SIZE,x))
dramIntersector.setNext(llbIntersector)
llbIntersector.setNext(peArray)
peArray.setNext(peIntersectorList)

dramIntersector.input(input1,input2)
print(i1.toarray())
print(i2.toarray())
print_csf_tree(input1, depth=0)
print_csf_tree(input2, depth=0)

TypeError: LLBIntersector.__init__() missing 2 required positional arguments: 'matrix1LLBColSize' and 'PEColSize'

In [ ]:
print(dramIntersector)
dramIntersector.cycle()
print(dramIntersector)

DRAM StreamOne: [], StreamTwo: [], endFlag: False
DRAM StreamOne: [4, 2], StreamTwo: [3], endFlag: False
